### ISSUE TITLE
can i try first

### ISSUE THREAD

**Issue by johnfelipe** [JasonYao/university-video-meeter#7]
can i test in live demo url or screenshots may be?

**Comment by JasonYao** [comment]
Hey John,
Unfortunately right now we're still in a very early development phase, and still building out functionality. This means that our work is primarily in the back-end, leaving the front-end pretty basic.

You can actually run the dev build of this poject by following the [setup](https://github.com/JasonYao/university-video-meeter#setup) instructions.

Once we reach alpha/beta milestones, we'll add in a few gifs showcasing functionality, and link to the actual site in production.
